// Test generated by RoostGPT for test expressscriptsdemo using AI Type Open AI and AI Model gpt-4

package com.bootexample4.products.controller;

import static org.mockito.Mockito.when;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;

import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.springframework.http.ResponseEntity;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;

public class ProductController_updateProduct_9454a9af90_Test {

    @InjectMocks
    ProductController productController;

    @Mock
    ProductRepository productRepository;

    @Test
    public void testUpdateProduct_Success() {
        Product existingProduct = new Product();
        existingProduct.setName("Old Product");
        existingProduct.setDescription("Old Description");
        existingProduct.setPrice(100.0);

        Product newProduct = new Product();
        newProduct.setName("New Product");
        newProduct.setDescription("New Description");
        newProduct.setPrice(200.0);

        when(productRepository.findById(anyLong())).thenReturn(Optional.of(existingProduct));
        when(productRepository.save(any(Product.class))).thenReturn(newProduct);

        ResponseEntity<Product> responseEntity = productController.updateProduct(1L, newProduct);

        assertEquals(200, responseEntity.getStatusCodeValue());
        assertEquals(newProduct, responseEntity.getBody());
    }

    @Test
    public void testUpdateProduct_NotFound() {
        Product newProduct = new Product();
        newProduct.setName("New Product");
        newProduct.setDescription("New Description");
        newProduct.setPrice(200.0);

        when(productRepository.findById(anyLong())).thenReturn(Optional.empty());

        ResponseEntity<Product> responseEntity = productController.updateProduct(1L, newProduct);

        assertEquals(404, responseEntity.getStatusCodeValue());
    }
}
