/*
Test generated by RoostGPT for test metering-integration using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Create Metering Label\n' +
    '    When I send a POST request to "/v2.0/metering/metering-labels" with the following payload:\n' +
    '      """\n' +
    '      {\n' +
    '        "id": "bc91b832-8465-40a7-a5d8-ba87de442266",\n' +
    '        "tenant_id": "45345b0ee1ea477fac0f541b2cb79cd4",\n' +
    '        "description": "description of label1",\n' +
    '        "name": "label1"\n' +
    '      }\n' +
    '      """\n' +
    '    Then the response status code should be 201\n' +
    '    And the response should be in JSON\n' +
    '    And the response should contain the created metering label:\n' +
    '      | id                                   | tenant_id                           | description            | name   |\n' +
    '      | bc91b832-8465-40a7-a5d8-ba87de442266 | 45345b0ee1ea477fac0f541b2cb79cd4   | description of label1 | label1 |',
  title: 'Create Metering Label'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.jupiter.api.Test;
import static org.hamcrest.Matchers.*;
import static io.restassured.RestAssured.given;

public class CreateMeteringLabelTest {

    @Test
    public void createMeteringLabel() {

        // Define the base URL
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");

        // Define the payload
        String payload = "{" +
                "\"id\": \"bc91b832-8465-40a7-a5d8-ba87de442266\"," +
                "\"tenant_id\": \"45345b0ee1ea477fac0f541b2cb79cd4\"," +
                "\"description\": \"description of label1\"," +
                "\"name\": \"label1\"" +
                "}";

        // Send a POST request and validate the response
        Response response = given()
                .contentType(ContentType.JSON)
                .body(payload)
                .when()
                .post("/v2.0/metering/metering-labels");

        response.then()
                .statusCode(201) // Assert Status code
                .body("id", equalTo("bc91b832-8465-40a7-a5d8-ba87de442266")) // Assert ID in response
                .body("tenant_id", equalTo("45345b0ee1ea477fac0f541b2cb79cd4")) // Assert tenant_id in response
                .body("description", equalTo("description of label1")) // Assert description in response
                .body("name", equalTo("label1")); // Assert name in response
    }
}
