/*
Test generated by RoostGPT for test Integration-RestAssuredTest using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Delete an existing product\r\n' +
    '    Given there is an existing product with ID 1\r\n' +
    '    When the client sends a DELETE request to "/api/products/1"\r\n' +
    '    Then the response status code should be 200\r\n' +
    '    And the product with ID 1 should no longer exist',
  title: 'Delete an existing product'
}

*/
package com.bootexample4.RoostTest;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static org.hamcrest.Matchers.equalTo;

public class deleteAnExistingProductTest {

    @Test
    public void deleteAnExistingProduct() {
        // Set the base URL
        String baseUrl = System.getenv("ROOST_SERVER_URL");

        // Given there is an existing product with ID 1
        int productId = 1;

        // When the client sends a DELETE request to "/api/products/1"
        RequestSpecification request = given().baseUri(baseUrl)
                                              .pathParam("productId", productId)
                                              .contentType(ContentType.JSON);
        Response response = request.when().delete("/products/{productId}");

        // Then the response status code should be 200
        response.then().statusCode(200);

        // And the product with ID 1 should no longer exist
        // Send a GET request to verify the product was deleted
        Response getResponse = request.when().get("/products/{productId}");
        getResponse.then().statusCode(404);
    }
}
