/*
Test generated by RoostGPT for test metering-integration using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Delete Metering Label Rule\n' +
    '    When I send a DELETE request to "/v2.0/metering/metering-label-rules/9536641a-7d14-4dc5-afaf-93a973ce0eb8"\n' +
    '    Then the response status code should be 204',
  title: 'Delete Metering Label Rule'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.junit.Before;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;

public class deleteMeteringLabelRuleTest {

    @Before
    public void setup() {
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");
    }

    @Test
    public void deleteMeteringLabelRule() {
        // Send a DELETE request to "/v2.0/metering/metering-label-rules/9536641a-7d14-4dc5-afaf-93a973ce0eb8"
        Response response = given()
                .contentType(ContentType.JSON)
                .delete("/v2.0/metering/metering-label-rules/9536641a-7d14-4dc5-afaf-93a973ce0eb8");

        // The response status code should be 204
        response.then()
                .statusCode(204);
    }
}
