/*
Test generated by RoostGPT for test metering-integration using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Delete Metering Label\n' +
    '    When I send a DELETE request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"\n' +
    '    Then the response status code should be 204',
  title: 'Delete Metering Label'
}

*/
package com.bootexample4.RoostTest;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;
import static org.hamcrest.Matchers.*;

public class deleteMeteringLabelTest {

    @Test
    public void testDeleteMeteringLabel() {
        // Define base URL
        String ROOST_SERVER_URL = System.getenv("ROOST_SERVER_URL");
        String BASE_URL = ROOST_SERVER_URL + "/v2.0/metering/metering-labels/";
        String meteringLabelId = "a6700594-5b7a-4105-8bfe-723b346ce866";

        // Send DELETE request
        Response response = given()
            .contentType(ContentType.JSON)
            .when()
            .delete(BASE_URL + meteringLabelId);

        // Validate the response
        response.then()
            .assertThat()
            .statusCode(204);
    }
}
