/*
Test generated by RoostGPT for test Integration-RestAssuredTest using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Get all products\r\n' +
    '    When the client sends a GET request "/api/products" to get the list of all products\r\n' +
    '    Then the list of products returned should be empty',
  title: 'Get all products'
}

*/
package com.bootexample4.RoostTest;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import org.testng.Assert;
import org.testng.annotations.Test;

import static io.restassured.RestAssured.given;

public class getAllProductsTest {

    @Test
    public void testGetAllProducts() {
        // Define base URL
        RestAssured.baseURI = System.getenv("ROOST_SERVER_URL");

        // Send GET request and store response
        Response response = given()
                .contentType(ContentType.JSON)
                .get("/api/products");

        // Assert that the response status is 200
        Assert.assertEquals(response.getStatusCode(), 200, "Expected response code is 200.");

        // Assert that the response body is empty
        String responseBody = response.getBody().asString();
        Assert.assertEquals(responseBody, "[]", "Expected response body to be an empty list.");
    }
}
