/*
Test generated by RoostGPT for test metering-integration using AI Type Open AI and AI Model gpt-4

{
  background: null,
  rule: null,
  scenario: 'Show Metering Label\n' +
    '    When I send a GET request to "/v2.0/metering/metering-labels/a6700594-5b7a-4105-8bfe-723b346ce866"\n' +
    '    Then the response status code should be 200\n' +
    '    And the response should be in JSON\n' +
    '    And the response should contain the metering label:\n' +
    '      | id                                   | tenant_id                           | description            | name   |\n' +
    '      | a6700594-5b7a-4105-8bfe-723b346ce866 | 45345b0ee1ea477fac0f541b2cb79cd4   | label1 description     | label1 |',
  title: 'Show Metering Label'
}

*/
package com.bootexample4.RoostTest;

import org.junit.jupiter.api.Test;
import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.equalTo;
import io.restassured.http.ContentType;
import io.restassured.response.Response;

public class showMeteringLabelTest {

    @Test
    public void showMeteringLabel() {

        // Define the base url
        String baseUrl = System.getenv("ROOST_SERVER_URL") + "/v2.0/metering/metering-labels";

        // Define the id of the metering label to be fetched
        String meteringLabelId = "a6700594-5b7a-4105-8bfe-723b346ce866";

        // Send GET request to fetch metering label
        Response response = given()
            .contentType(ContentType.JSON)
            .get(baseUrl + "/" + meteringLabelId);

        // Verify the response status code is 200
        response.then()
            .statusCode(200);

        // Verify the response is in JSON format
        response.then()
            .contentType(ContentType.JSON);

        // Verify the response contains the expected metering label
        response.then()
            .body("id", equalTo("a6700594-5b7a-4105-8bfe-723b346ce866"))
            .body("tenant_id", equalTo("45345b0ee1ea477fac0f541b2cb79cd4"))
            .body("description", equalTo("label1 description"))
            .body("name", equalTo("label1"));
    }
}
